import java.util.List;
import java.util.ArrayList;
import java.io.File;
import java.util.Scanner;
import java.io.IOException;
import java.util.Iterator;
import java.util.Collections;

public class Backend implements BackendInterface {
	private	IterableSortedCollection<SongInterface> songTree; // tree to get and find songs

	private int energyFilter; // filter of energy used to modify ranges of danceability of songs

	private List<SongInterface> songList; // record of range of songs user calls on

	private List<String> range; //range of songs generated by get range	
	

	/**
	 * Initailzes all fields of the backend of this music app including the song range and the energy filter.
	 */
	public Backend(IterableSortedCollection<SongInterface> tree){
		this.energyFilter = -1;
		this.songList = new ArrayList<>();
		this.range = new ArrayList<>();
		this.songTree = tree;
	}

  	/**
 	  * Loads data from the .csv file referenced by filename.
	  * @param filename is the name of the csv file to load data from
	  * @throws IOException when there is trouble finding/reading file
	  */
	@Override
	public void readData(String filename) throws IOException{

		// check if the user entered the right file name
		if(!filename.equals("songs.csv")){
		throw new IOException();
		}

		// open the file
		File file = new File(filename);
		
		// scan the file line by line		
		Scanner scanner = new Scanner(file);
		scanner.nextLine();
		while(scanner.hasNext()){
			//create a song from each line in the file and insert it into the tree data structure
			Song song = new Song(scanner.nextLine());
			songTree.insert(song);
		}

		scanner.close();
	
	}

    	/**
    	 * Retrieves a list of song titles for songs that have a Danceability
    	 * within the specified range (sorted by Danceability in ascending order).
    	 * If a minEnergy filter has been set using filterEnergeticSongs(), then 
    	 * only songs with an energy rating greater than or equal to this minEnergy
    	 * should be included in the list that is returned by this method.
    	 *
    	 * Note that either this danceability range, or the resulting unfiltered 
    	 * list of songs should be saved for later use by the other methods 
    	 * defined in this class.
    	 *
    	 * @param low is the minimum Danceability of songs in the returned list
    	 * @param hight is the maximum Danceability of songs in the returned list
    	 * @return List of titles for all songs in specified range 
    	 */
	 @Override
   	 public List<String> getRange(int low, int high){

		// create list to keep track of songs in the range
		List<SongInterface> songList = new ArrayList<>();

		// set up iterator
		songTree.setIterationStartPoint(null);
		Iterator<SongInterface> iterator = songTree.iterator();

		// go through song tree and find songs that are within the danceability range
		while(iterator.hasNext()){
			SongInterface song = iterator.next();
			if(song.getDanceability() < low || song.getDanceability() > high){
				continue;
			}
			songList.add(song);
		}

		// make changes to range if energy filter is set to something else
		if(energyFilter != -1){

			// get rid of all songs that are below the energy filter
			for(int i = 0; i < songList.size(); i++){
				if( songList.get(i).getEnergy() < energyFilter){
					songList.remove(i);
					i--;
				} 
			}

		}
		// make our updated song List into a list of song titles to be used as the range
                List<String> result = new ArrayList<>();
                for(SongInterface song : songList){
                	result.add(song.getTitle());
                }
		this.range = result;
		this.songList = songList;
		return result;
	}

	/**
     	* Filters the list of songs returned by future calls of getRange() and 
     	* fiveFastest() to only include energetic songs.  If getRange() was 
     	* previously called, then this method will return a list of song titles
     	* (sorted in ascending order by Danceability) that only includes songs on
     	* with the specified minEnergy or higher.  If getRange() was not 
     	* previously called, then this method should return an empty list.
     	*
     	* Note that this minEnergy threshold should be saved for later use by the 
     	* other methods defined in this class.
     	*
     	* @param minEnergy is the minimum energy of songs that are returned
     	* @return List of song titles, empty if getRange was not previously called
     	*/
    	public List<String> filterEnergeticSongs(int minEnergy){

		
		// update the energy filter
		this.energyFilter = minEnergy;

		// check if range was not previously called
		if(this.range.isEmpty()) return new ArrayList<String>();

		// make a deepish copy of our songlist to use and modify in this method
		List<SongInterface> songs = new ArrayList<>();
		for(SongInterface song : this.songList){
			songs.add(song);
		}

		// iterate through the deepish copy of the songList array to remove any songs because of the filter
		for(int i = 0; i < songs.size(); i++){
			if(songs.get(i).getEnergy() < this.energyFilter){
				songs.remove(i);
				i--;
			}
		}

		// create a array with the titles of the songs and return it
		List<String> result = new ArrayList<>();
		for(SongInterface song :  songs){
			result.add(song.getTitle());
		}

		return result;
	}

	/**
     	* This method makes use of the attribute range specified by the most
     	* recent call to getRange().  If a minEnergy threshold has been set by
     	* filterEnergeticSongs() then that will also be utilized by this method.
     	* Of those songs that match these criteria, the five fastest will be 
     	* returned by this method as a List of Strings in increasing order of 
     	* danceability.  Each string contains the speed in BPM followed by a 
     	* colon, a space, and then the song's title.
     	* If fewer than five such songs exist, return all of them.
     	*
     	* @return List of five fastest song titles and their respective speeds
     	* @throws IllegalStateException when getRange() was not previously called.
     	*/
    	public List<String> fiveFastest(){

		//first check if the range was never called on
		if(this.range.isEmpty()) throw new IllegalStateException();

		// create a result array of song objects and a deepish copy of our existing song list
		List<SongInterface> resultSongs = new ArrayList<>();
		List<SongInterface> songs = new ArrayList<>();
		for(SongInterface song : this.songList){
                        songs.add(song);
                }

		// remove some of the songs dependeing on if a energy filter was set
		if(energyFilter != -1){
			for(int i = 0; i < songs.size(); i++){
                		if(songs.get(i).getEnergy() < this.energyFilter){
                                	songs.remove(i);
					i--;
                        	}	
                	}

		}




		// determine the amount of songs in the fast range
		int iterations = 5;
		if(songs.size() < 5) iterations = songs.size(); 

		// go through five or lower iterations through the new songlist, finding the biggest one and removing it and puting it in our result list
		for(int i = 0; i < iterations;i++){
			SongInterface fastest = null;
			for(int j = 0; j < songs.size();j++){
				if(fastest == null) fastest = songs.get(j);
				else if(songs.get(j).getBPM() > fastest.getBPM()) fastest = songs.get(j);  
			}
			songs.remove(fastest);
			resultSongs.add(fastest);

		}

		// re-sort the array based on danceability
		Collections.sort(resultSongs);

		// change format of answer to one specified in javadoc
		List<String> result = new ArrayList<>();
			for(SongInterface song: resultSongs){
                        	String toAdd = song.getBPM() + ": " + song.getTitle();
                        	result.add(toAdd);
			}
		
		return result;

}
}
