import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import java.util.ArrayList;
import java.util.List;
import java.io.IOException;

/**
 * This class provides unit tests for all four methods in the Backend Interface.
 */
public class BackendDeveloperTests {

	/**
	 * This testor method test's the read data method in its ability to throw a IOException when there is trouble finding the file.
	 */
	@Test
	public void readDataErrorTest(){
		// create reference to backend
		BackendInterface backend = new Backend(new ISCPlaceholder());
		String error = "error";
		// make sure this call to read Data is throwing a IO Excpetion
		Assertions.assertThrows(IOException.class, () -> {
			backend.readData(error);});
	}
	/**
	 * This testor method tes'ts the read data method in its ability to read the songs.csv file properly. In addition, it also makes sure it reads all the data in the csv file.
	 */
	@Test
	public void readDataAll(){
		// create reference to backend
		IterableSortedCollection iscp = new ISCPlaceholder();
		BackendInterface backend = new Backend(iscp);

		// make sure that reading the songs.csv file does not throw any exceptions
		Assertions.assertDoesNotThrow(() -> {
			backend.readData("songs.csv");});

		// make sure that read the songs.csv file reads all the lines it should read.
		Assertions.assertEquals(603, iscp.size());
		


	}




	/**
	 * This testor method test's the get Range method's ability to return a list of songs within a certain dancibility range and after a energy filter has been applied.
	 */
	@Test
	public void getRangeTests(){
		IterableSortedCollection<SongInterface> iscp = new ISCPlaceholder();
		// create reference to backend
		BackendInterface backend = new Backend(iscp);

		// get result from calling on get range
		List<String> result = backend.getRange(95, 97);
		
		// create expected result
		List<String> expectedResult = new ArrayList<>();
		expectedResult.add("Anaconda");
		expectedResult.add("Bad Liar");
		expectedResult.add("Drip (feat. Migos)");

		// make sure result returned form get range call is correct
		Assertions.assertIterableEquals(expectedResult, result);
		
		// run get range after filter is called
		backend.filterEnergeticSongs(50);
		List<String> result2 = backend.getRange(95, 97);
		List<String> expectedResult2 = new ArrayList<>();
		expectedResult2.add("Anaconda");
		expectedResult2.add("Drip (feat. Migos)"); 

		Assertions.assertIterableEquals(expectedResult2, result2);


	} 

	/**
	 * This testor method test's the filter Energetic Song method's ability to return a list of songs that are in a certain dancibility range 
	 * and meet or are greater than the minium Energetic value. This testor also test's the method's ability to not save results after calling it again.
	 */
	@Test
	public void filterEnergeticSongsTests(){

		//create reference to backend
		BackendInterface backend = new Backend(new ISCPlaceholder());

		// create a range of songs to use for the filter Energetic song method
		backend.getRange(95, 97);

		// call on filter Energetic song method and record its result
                List<String> result = backend.filterEnergeticSongs(50);

		// create expected result
		List<String> expectedResult = new ArrayList<>();
		expectedResult.add("Anaconda");
		expectedResult.add("Drip (feat. Migos)");

		// make sure result is correct
		Assertions.assertIterableEquals(expectedResult, result);
	
		// reseting the filter before calling on get range to test that it doesn't modify the saved range until range is called
		backend.filterEnergeticSongs(-1);
		
		// call on range again with same parameters to test no change
		List<String> result2 = backend.getRange(95, 97);
		List<String> expectedResult2 = new ArrayList<>();
                expectedResult2.add("Anaconda");
		expectedResult2.add("Bad Liar");
                expectedResult2.add("Drip (feat. Migos)");
	
		Assertions.assertIterableEquals(expectedResult2, result2);

	}


	/**
         * This testor method test's the five fastest method's ability to return the top 5 fastest songs in a list of songs that was previously generated by the get range method. 
	 * Shows that having under 5 songs will allow the method to fucntion normally.
         */
	@Test
	public void fiveFastestTest(){

		//create reference to backend
		BackendInterface backend = new Backend(new ISCPlaceholder());

		// create a range of songs to use for the five fastest method
                backend.getRange(95, 97);

		// call on five fastest and record its result
		List<String> result = backend.fiveFastest();

		// create expected result
		List<String> expectedResult = new ArrayList<>();
		expectedResult.add("130: Anaconda");
                expectedResult.add("121: Bad Liar");
                expectedResult.add("130: Drip (feat. Migos)");

		// make sure result is correct
		Assertions.assertIterableEquals(expectedResult, result,"" +  result.isEmpty());



	}

	/**
         * This testor method test's the five fastest method's ability to throw an Illegal State Exception when get Range is not previously called to generate a list of songs.
         */
	@Test
	public void fiveFastestTestError(){

		//create reference to backend
		 BackendInterface backend = new Backend(new ISCPlaceholder());

		// make sure this call to five fastest is throwing a Illegal State Excpetion
		 Assertions.assertThrows( IllegalStateException.class, () -> {
			backend.fiveFastest();});
	}

	/**
	 * Checks the frontend output when a get range is called on the backend with a range of 87 - 90.
	 */
	@Test
	public void integrationTestGetRange(){

		//initalize scanner, backend, and frontend
		String input = "87 - 90";
		Scanner scanner = new Scanner(System.in);		
		TextUITester textUI = new TextUITester(input);
		BackendInterface backend = new Backend(new ISCPlaceholder());
		FrontendInterface frontend = new FrontendInterface(scanner, backend);
	
		// get the output for the get range call
		frontend.getValues();
		String output = textUI.checkOutput();
		scanner.close();

		// create expected result from the output
		String expected = """7 songs found between 87 - 90:  Treasure Worth It Spark The Fire Dangerous Strip That Down (feat. Quavo) There's Nothing Holdin' Me Back Talk (feat. Disclosure)""";
		
		// make sure output from frontend had the right output from the implementation of the backend
		Assertions.assertEquals(expected, output);
	}

	/**
	 * Checks the frotend output when a five fastest is called on the backend after get range is called with a range of 87 - 90
	 */
	@Test
	public void integrationTestFiveFastest(){
	
		//initalize scanner, backend, and frontend
		String input = "87 - 90";
                Scanner scanner = new Scanner(System.in);               
                TextUITester textUI = new TextUITester(input);
                BackendInterface backend = new Backend(new ISCPlaceholder());
                FrontendInterface frontend = new FrontendInterface(scanner, backend);

		// get the output for the five fastest call
		frontend.getValues();
		frontend.topFive();
                String output = textUI.checkOutput();
                scanner.close()

		// create expected result from the output
		String expected = """5 fastest songs found between 87 - 90: Dangerous Treasure Spark The Fire There's Nothing Holdin' Me Back Talk (feat. Disclosure)""";
		
		// make sure output from frontend had the right output from the implementation of the backend
		Assertions.assertEquals(expected, output);
	} 




}
