import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import java.util.ArrayList;
import java.util.List;
import java.io.IOException;

/**
 * This class provides unit tests for all four methods in the Backend Interface.
 */
public class BackendDeveloperTests {

	/**
	 * This testor method test's the read data method in its ability to throw a IOException when there is trouble finding the file.
	 */
	@Test
	public void readDataTest(){
		//create reference to backend
		BackendInterface backend = new BackendPlaceholder(new ISCPlaceholder());
		
		// make sure this call to read Data is throwing a IO Excpetion
		Assertions.assertThrows(IOException.class, () -> {
			backend.readData("song.csv");});
	}

	/**
	 * This testor method test's the get Range method's ability to return a list of songs within a certain dancibility range.
	 */
	@Test
	public void getRangeTest(){

		//create reference to backend
		BackendInterface backend = new BackendPlaceholder(new ISCPlaceholder());

		// get result from calling on get range
		List<String> result = backend.getRange(95, 97);
		
		// create expected result
		List<String> expectedResult = new ArrayList<>();
		expectedResult.add("Anaconda");
		expectedResult.add("Bad Liar");
		expectedResult.add("Drip (feat. Migos)");

		// make sure result returned form get range call is correct
		Assertions.assertIterableEquals(expectedResult, result);


	} 

	/**
	 * This testor method test's the filter Energetic Song method's ability to return a list of songs that are in a certain dancibility range and meet or are greater than the minium Energetic value.
	 */
	@Test
	public void filterEnergeticSongsTest(){

		//create reference to backend
		BackendInterface backend = new BackendPlaceholder(new ISCPlaceholder());

		// create a range of songs to use for the filter Energetic song method
		backend.getRange(95, 97);

		// call on filter Energetic song method and record its result
                List<String> result = backend.filterEnergeticSongs(50);

		// create expected result
		List<String> expectedResult = new ArrayList<>();
		expectedResult.add("Anaconda");
		expectedResult.add("Drip (feat. Migos)");

		// make sure result is correct
		Assertions.assertIterableEquals(expectedResult, result);
	}


	/**
         * This testor method test's the five fastest method's ability to return the top 5 fastest songs in a list of songs that was previously generated by the get range method.
         */
	@Test
	public void fiveFastestTest1(){

		//create reference to backend
		BackendInterface backend = new BackendPlaceholder(new ISCPlaceholder());

		// create a range of songs to use for the five fastest method
                backend.getRange(95, 97);

		// call on five fastest and record its result
		List<String> result = backend.fiveFastest();

		// create expected result
		List<String> expectedResult = new ArrayList<>();
		expectedResult.add("130: Anaconda");
                expectedResult.add("121: Bad Liar");
                expectedResult.add("130: Drip (feat. Migos)");

		// make sure result is correct
		Assertions.assertIterableEquals(expectedResult, result);



	}

	/**
         * This testor method test's the five fastest method's ability to throw an Illegal State Exception when get Range is not previously called to generate a list of songs.
         */
	@Test
	public void fiveFastestTest2(){

		//create reference to backend
		 BackendInterface backend = new BackendPlaceholder(new ISCPlaceholder());

		// make sure this call to five fastest is throwing a Illegal State Excpetion
		 Assertions.assertThrows( IllegalStateException.class, () -> {
			backend.fiveFastest();});
	} 




}
