import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import java.util.ArrayList;
import java.util.List;
import java.io.IOException;
import java.util.Scanner;
/**
 * This class provides unit tests for all four methods in the Backend Interface.
 */
public class BackendDeveloperTests {

	/**
	 * This testor method test's the read data method in its ability to throw a IOException when there is trouble finding the file.
	 */
	@Test
	public void readDataErrorTest(){
		// create reference to backend
		BackendInterface backend = new Backend(new ISCPlaceholder());
		String error = "error";
		// make sure this call to read Data is throwing a IO Excpetion
		Assertions.assertThrows(IOException.class, () -> {
			backend.readData(error);});
	}
	/**
	 * This testor method test's the read data method in its ability to read the songs.csv file properly. In addition, it also makes sure it reads all the data in the csv file.
	 */
	@Test
	public void readDataAll(){
		// create reference to backend
		IterableSortedCollection iscp = new ISCPlaceholder();
		BackendInterface backend = new Backend(iscp);

		// make sure that reading the songs.csv file does not throw any exceptions
		Assertions.assertDoesNotThrow(() -> {
			backend.readData("songs.csv");});

		// make sure that read the songs.csv file reads all the lines it should read.
		Assertions.assertEquals(603, iscp.size());
		


	}




	/**
	 * This testor method test's the get Range method's ability to return a list of songs within a certain dancibility range and after a energy filter has been applied.
	 */
	@Test
	public void getRangeTests(){
		IterableSortedCollection<SongInterface> iscp = new ISCPlaceholder();
		// create reference to backend
		BackendInterface backend = new Backend(iscp);

		// get result from calling on get range
		List<String> result = backend.getRange(95, 97);
		
		// create expected result
		List<String> expectedResult = new ArrayList<>();
		expectedResult.add("Anaconda");
		expectedResult.add("Bad Liar");
		expectedResult.add("Drip (feat. Migos)");

		// make sure result returned form get range call is correct
		Assertions.assertIterableEquals(expectedResult, result);
		
		// run get range after filter is called
		backend.filterEnergeticSongs(50);
		List<String> result2 = backend.getRange(95, 97);
		List<String> expectedResult2 = new ArrayList<>();
		expectedResult2.add("Anaconda");
		expectedResult2.add("Drip (feat. Migos)"); 

		Assertions.assertIterableEquals(expectedResult2, result2);


	} 

	/**
	 * This testor method test's the filter Energetic Song method's ability to return a list of songs that are in a certain dancibility range 
	 * and meet or are greater than the minium Energetic value. This testor also test's the method's ability to not save results after calling it again.
	 */
	@Test
	public void filterEnergeticSongsTests(){

		//create reference to backend
		BackendInterface backend = new Backend(new ISCPlaceholder());

		// create a range of songs to use for the filter Energetic song method
		backend.getRange(95, 97);

		// call on filter Energetic song method and record its result
                List<String> result = backend.filterEnergeticSongs(50);

		// create expected result
		List<String> expectedResult = new ArrayList<>();
		expectedResult.add("Anaconda");
		expectedResult.add("Drip (feat. Migos)");

		// make sure result is correct
		Assertions.assertIterableEquals(expectedResult, result);
	
		// reseting the filter before calling on get range to test that it doesn't modify the saved range until range is called
		backend.filterEnergeticSongs(-1);
		
		// call on range again with same parameters to test no change
		List<String> result2 = backend.getRange(95, 97);
		List<String> expectedResult2 = new ArrayList<>();
                expectedResult2.add("Anaconda");
		expectedResult2.add("Bad Liar");
                expectedResult2.add("Drip (feat. Migos)");
	
		Assertions.assertIterableEquals(expectedResult2, result2);

	}


	/**
         * This testor method test's the five fastest method's ability to return the top 5 fastest songs in a list of songs that was previously generated by the get range method. 
	 * Shows that having under 5 songs will allow the method to fucntion normally.
         */
	@Test
	public void fiveFastestTest(){

		//create reference to backend
		BackendInterface backend = new Backend(new ISCPlaceholder());

		// create a range of songs to use for the five fastest method
                backend.getRange(95, 97);

		// call on five fastest and record its result
		List<String> result = backend.fiveFastest();

		// create expected result
		List<String> expectedResult = new ArrayList<>();
		expectedResult.add("130: Anaconda");
                expectedResult.add("130: Drip (feat. Migos)");
                expectedResult.add("121: Bad Liar");

		// make sure result is correct
		Assertions.assertIterableEquals(expectedResult, result,"" +  result.isEmpty());



	}

	/**
         * This testor method test's the five fastest method's ability to throw an Illegal State Exception when get Range is not previously called to generate a list of songs.
         */
	@Test
	public void fiveFastestTestError(){

		//create reference to backend
		 BackendInterface backend = new Backend(new ISCPlaceholder());

		// make sure this call to five fastest is throwing a Illegal State Excpetion
		 Assertions.assertThrows( IllegalStateException.class, () -> {
			backend.fiveFastest();});
	}

	/**
	 * This testor method tests the frontend's output when a proper call to Read File is made.
	 */
	@Test
	public void integrationTestReadData(){
		
		// set up input, backend, and frontend 
	    	String input = "songs.csv";
		TextUITester textUI = new TextUITester(input);
		BackendInterface backend = new Backend(new IterableRedBlackTree<SongInterface>());
		Scanner scanner = new Scanner(System.in);
	    	FrontendInterface frontend = new Frontend(scanner, backend);

		// get output for the read Data/read File call from the frontend
	    	frontend.readFile();
	    	String output = textUI.checkOutput();
	    	scanner.close();

		// make sure frontend outputs correct output retrieved from backend
		Assertions.assertTrue(output.contains("Done reading file"));

	}

	/**
	 * This testor method tests the frontend's output when a call to Get Range is called on a range between a danceability of 87 - 40.
	 */
	@Test
	public void integrationTestGetRange(){

		// set up input, backend, and frontend 
		String input = "songs.csv\n87 - 90";
                TextUITester textUI = new TextUITester(input);
                BackendInterface backend = new Backend(new IterableRedBlackTree<SongInterface>());
                Scanner scanner = new Scanner(System.in);
                FrontendInterface frontend = new Frontend(scanner, backend);

		// get output for the get Values/get Range call on a range between 87 - 90 from the frontend
            	frontend.readFile();
		frontend.getValues();
            	String output = textUI.checkOutput();
            	scanner.close();

		// make sure frontend outputs correct output retrieved from backend
		Assertions.assertTrue(output.contains("7 songs found between 87 - 90:\nThere's Nothing Holdin' Me Back\nStrip That Down (feat. Quavo)\nTreasure\nSpark The Fire\nWorth It\nTalk (feat. Disclosure)\nDangerous"));
	}


	/**
	 * This testor method tests the frontend's output when a call to five fastest is called on a range between a danceability of 87 - 90.
	 */
	@Test
	public void partnerTestFiveFastest(){

		// set up input, backend, and frontend
		String input = "songs.csv\n87 - 90";
                TextUITester textUI = new TextUITester(input);
                BackendInterface backend = new Backend(new IterableRedBlackTree<SongInterface>());
                Scanner scanner = new Scanner(System.in);
                FrontendInterface frontend = new Frontend(scanner, backend);

		// get output from the five fastest method call on a range between 87 - 90 from the frontend
                frontend.readFile();
                frontend.getValues();
		frontend.topFive();
                String output = textUI.checkOutput();
                scanner.close();

		// make sure frontend outputs correct output retrieved from backend
		Assertions.assertTrue(output.contains("Top Five songs found between 87 - 90\n122: There's Nothing Holdin' Me Back\n116: Treasure\n120: Spark The Fire\n136: Talk (feat. Disclosure)\n109: Dangerous"));


	}

	/**
	 * This testor method tests the frontend's output when a call to set filter is called on a range between a danceability of 87 - 90.
	 */
	@Test
	public void partnerTestSetFilter(){

		// set up input, backend, and frontend
		String input = "songs.csv\n87 - 90\n55";
                TextUITester textUI = new TextUITester(input);
                BackendInterface backend = new Backend(new IterableRedBlackTree<SongInterface>());
                Scanner scanner = new Scanner(System.in);
                FrontendInterface frontend = new Frontend(scanner, backend);

		// get output from the set filter  method call on a range between 87 - 90 from the frontend
		frontend.readFile();
		frontend.getValues();
		frontend.setFilter();
		String output = textUI.checkOutput();
		scanner.close();

		// make sure frontend outputs correct output retrieved from backend
		Assertions.assertTrue(output.contains("4 songs found between 87 - 90 with energy >= 55:\nThere's Nothing Holdin' Me Back\nTreasure\nSpark The Fire\nWorth It"));


	}

	@Test
	public void partnerTestTopFiveNoFile(){

		// set up input, backend, and frontend
                String input = "";
                TextUITester textUI = new TextUITester(input);
                Scanner scanner = new Scanner(System.in);
                FrontendInterface frontend = new Frontend(scanner, new BackendPlaceholder(null));

		frontend.topFive();	
		String output = textUI.checkOutput();
		scanner.close();
		Assertions.assertTrue(output.contains("There exists no file"));
		
	}

	@Test
	public void partnerTestTopFive(){
		String input = "";
		System.out.println("hi");
                TextUITester textUI = new TextUITester(input);
		 System.out.println("did not pass scanner");
                 Scanner scanner = new Scanner(System.in);
                 FrontendInterface frontend = new Frontend(scanner, new BackendPlaceholder(null));
		 System.out.println("did not pass scanner");
		frontend.getValues();
		//String output = textUI.checkOutput();
		//scanner.close();
		//Assertions.assertTrue(output.contains("This is not a valid command"));


	}

}	
